@startuml
'https://plantuml.com/object-diagram

object "<u>phpDemo1 : Folder </u>" as root {
    name = "Source Files"
}

object "<u>sourceFiles : Folder </u>" as sf {
    name = "Source Files"
}

object "<u>includePath : Folder </u>" as ip {
    name = "Include Path"
}

object "<u>remoteFiles : Folder </u>" as rf {
    name = "Remote Files"
}

object "<u>phalcon : Folder </u>" as ph {
    name = ".phalcon"
}

object "<u>app : Folder </u>" as app {
    name = "app"
}

object "<u>cache : Folder </u>" as cache {
    name = "cache"
}

root -- sf : subFolder
root -- ip : subFolder
root -- rf : subFolder

sf -- ph : subFolder
sf -- app : subFolder
sf -- cache : subFolder
@enduml
